name: Verify

# Controls when the action will run.
on:
  workflow_call:
    secrets:
      GITHUB_USERNAME:
        required: true
      GITHUB_TEST_TOKEN:
        required: true
      GITHUB_ORG:
        required: true
      GITHUB_HOST:
        required: true
      GHE_USERNAME:
        required: true
      GHE_TOKEN:
        required: true
      GHE_ORG:
        required: true
      GHE_HOST:
        required: true
      GITLAB_USERNAME:
        required: true
      GITLAB_TOKEN:
        required: true
      GITLAB_ORG:
        required: true
      GITLAB_HOST:
        required: true
      BITBUCKET_USERNAME:
        required: true
      BITBUCKET_TOKEN:
        required: true
      BITBUCKET_ORG:
        required: true
      BITBUCKET_HOST:
        required: true
      GITEA_USERNAME:
        required: true
      GITEA_TOKEN:
        required: true
      GITEA_ORG:
        required: true
      GITEA_HOST:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    container: quay.io/cloudnativetoolkit/terraform:v1.1

    strategy:
      matrix:
        testcase:
          - github
          - ghe
          - gitlab
          - bitbucket
          - gitea
      fail-fast: false

    env:
      HOME: /home/devops

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - id: variables
        name: Set up variables
        env:
          GIT_ORG: ${{ secrets.GIT_ORG }}
        shell: bash
        run: |
          repo=$(echo ${GITHUB_REPOSITORY} | sed -E "s~.*/[^-]+-(.*)~\1~g")
          echo "Repo: $repo"
          echo "::set-output name=repo::$repo"
          
          case ${{ matrix.testcase }} in
            github)
              echo "::set-output name=username::${{ secrets.GITHUB_USERNAME }}"
              echo "::set-output name=token::${{ secrets.GITHUB_TEST_TOKEN }}"
              echo "::set-output name=org::${{ secrets.GITHUB_ORG }}"
              echo "::set-output name=host::${{ secrets.GITHUB_HOST }}"
              ;;
            ghe)
              echo "::set-output name=username::${{ secrets.GHE_USERNAME }}"
              echo "::set-output name=token::${{ secrets.GHE_TOKEN }}"
              echo "::set-output name=org::${{ secrets.GHE_ORG }}"
              echo "::set-output name=host::${{ secrets.GHE_HOST }}"
              ;;
            gitlab)
              echo "::set-output name=username::${{ secrets.GITLAB_USERNAME }}"
              echo "::set-output name=token::${{ secrets.GITLAB_TOKEN }}"
              echo "::set-output name=org::${{ secrets.GITLAB_ORG }}"
              echo "::set-output name=host::${{ secrets.GITLAB_HOST }}"
              ;;
            bitbucket)
              echo "::set-output name=username::${{ secrets.BITBUCKET_USERNAME }}"
              echo "::set-output name=token::${{ secrets.BITBUCKET_TOKEN }}"
              echo "::set-output name=org::${{ secrets.BITBUCKET_ORG }}"
              echo "::set-output name=host::${{ secrets.BITBUCKET_HOST }}"
              ;;
            gitea)
              echo "::set-output name=username::${{ secrets.GITEA_USERNAME }}"
              echo "::set-output name=token::${{ secrets.GITEA_TOKEN }}"
              echo "::set-output name=org::${{ secrets.GITEA_ORG }}"
              echo "::set-output name=host::${{ secrets.GITEA_HOST }}"
              ;;
            *)
              echo "Unrecognized git server type: ${{ matrix.testcase }}" >&2
              exit 1
              ;;
          esac

      - name: Verify deploy on ${{ matrix.testcase }}
        uses: cloud-native-toolkit/action-module-verify-deploy@main
        with:
          clusterId: ${{ matrix.testcase }}
          validateDeployScript: .github/scripts/validate-deploy.sh
        env:
          TF_VAR_git_username: ${{ steps.variables.outputs.username }}
          TF_VAR_git_token: ${{ steps.variables.outputs.token }}
          TF_VAR_git_org: ${{ steps.variables.outputs.org }}
          TF_VAR_git_repo: ${{ steps.variables.outputs.repo }}
          TF_VAR_git_host: ${{ steps.variables.outputs.host }}

      - name: Verify destroy on ${{ matrix.testcase }}
        uses: cloud-native-toolkit/action-module-verify-destroy@main
        if: ${{ always() }}
        with:
          clusterId: ${{ matrix.testcase }}
        env:
          TF_VAR_git_username: ${{ steps.variables.outputs.username }}
          TF_VAR_git_token: ${{ steps.variables.outputs.token }}
          TF_VAR_git_org: ${{ steps.variables.outputs.org }}
          TF_VAR_git_repo: ${{ steps.variables.outputs.repo }}
          TF_VAR_git_host: ${{ steps.variables.outputs.host }}
